// Generated by CoffeeScript 1.6.3
(function() {
  exports.serverList = require('../../config/servers.json').servers;

  exports.connectToServer = function(serverName) {
    var anyDB, conn, dbURL, dotenv, sql;
    dotenv = require('dotenv');
    dotenv.load();
    anyDB = require('any-db-postgres');
    dbURL = process.env["" + (serverName.toUpperCase()) + "_URL"];
    conn = anyDB.createConnection(dbURL);
    sql = "SELECT '" + serverName + "' as SERVER, NOW() as THETIME;";
    return conn.query(sql).on('row', function(row) {
      console.log(row);
      return conn.end();
    });
  };

}).call(this);
